hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}-${method}-${ls}
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: ""
dataset_root: ""
workdir: ""
log_path: "metrics.json"
model_name: "ViT-B/16"
prompt_template: "a bad photo of a {}."

batch_size: 64
increment: ${initial_increment}
initial_increment: 2  
scenario: "class"
dataset: "cifar100"

# method: "zeroshot"
# lr: 7.1e-6
# ls: 0.3
# we: 1
# avg_freq: 10
# ref_dataset: "conceptual_captions"
# ref_sentences: "conceptual_captions"


weight_decay: 0.0
l2: 0
ce_method: 0

method: "MoE-Adapters"
lr: 1e-3
ls: 0.0
#we:
#avg_freq:
#ref_dataset:
#ref_sentences: random

